{
  "openapi": "3.0.0",
  "info": {
    "title": "SNAP E-Wallet API",
    "version": "1.0.0",
    "description": "Backend Integration to check status API"
  },
  "servers": [
    {
      "url": "https://api-sandbox.doku.com/orders/v1.0/debit/status",
      "description": "Sandbox environment"
    },
    {
      "url": "https://api.doku.com/orders/v1.0/debit/status",
      "description": "Production environment"
    }
  ],
  "paths": {
    "/orders/v1.0/debit/status": {
      "post": {
        "summary": "Check status E-Wallet",
        "description": "Backend Integration to check status API",
        "operationId": "Check status E-Wallet",
        "parameters": [
          {
            "name": "X-TIMESTAMP",
            "in": "header",
            "description": "Client's current local time with format : YYYY-MM-DDTHH:mm:ssZD",
            "required": true,
            "schema": {
              "type": "string",
              "example": "2020-12-21T14:56:11+07:00"
            }
          },
          {
            "name": "X-SIGNATURE",
            "in": "header",
            "description": "Represents signature of a request. ",
            "required": true,
            "schema": {
              "type": "string",
              "example": "ieNOENDdN4MnectGytx5UvmOfASZ2oGWMCJ8gVqkw3tB98ofgY9cbxSeY4IYoYeoKs+0QP4h8BTBhemlfeXp1w=="
            }
          },
          {
            "name": "X-PARTNER-ID",
            "in": "header",
            "description": "Client ID for merchant that generated by DOKU",
            "required": true,
            "schema": {
              "type": "string",
              "example": "82150823919040624621823174737537"
            }
          },
          {
            "name": "X-EXTERNAL-ID",
            "in": "header",
            "description": "Reference number that should be unique in the same day or to be known as Request ID",
            "required": true,
            "schema": {
              "type": "string",
              "example": "41807553358950093184162180797837"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Represents access_token of a request; Keyword starts with “Bearer ” followed by access_token ",
            "required": true,
            "schema": {
              "type": "string",
              "example": "bearer gp9HjjEj813Y9JGoqwOeOPWbnt4CUpvIJbU1mMU4a11MNDZ7Sg5u9a"
            }
          },
          {
            "name": "Content type",
            "in": "header",
            "description": "The media type of the resource ",
            "required": true,
            "schema": {
              "type": "string",
              "example": "application/ json"
            }
          }
        ],
        "requestBody": {
          "description": "Here is the sample of request body to get status of E-Wallet : ",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBody"
              },
              "examples": {
                "requestBody": {
                  "summary": "Request Body",
                  "value": {
                    "originalPartnerReferenceNo": "INV_SHOPEE_202407250004",
                    "serviceCode": "55",
                    "transactionDate": "2020-12-21T14:56:11+07:00",
                    "amount": {
                      "value": "2000.00",
                      "currency": "IDR"
                    },
                    "merchantId": "23489182303312",
                    "subMerchantId": "23489182303312",
                    "externalStoreId": "183908924912387",
                    "additionalInfo": {
                      "deviceId": "12345679237",
                      "channel": "mobilephone"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The response will be similar to HTTP notification. Some parameters might not be presented in certain status cases, please check our Postman Collection to try it yourself.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    { "$ref": "#/components/schemas/OVOSalePending" },
                    { "$ref": "#/components/schemas/OVOSaleSuccess" },
                    { "$ref": "#/components/schemas/OVOSaleRefund" },
                    {
                      "$ref": "#/components/schemas/OVO-OpenAPIRecurring-SuccessPayment"
                    },
                    {
                      "$ref": "#/components/schemas/OVO-OpenAPIRecurring-Refund"
                    },
                    { "$ref": "#/components/schemas/ShopeePay-Pending" },
                    { "$ref": "#/components/schemas/ShopeePay-Success" },
                    { "$ref": "#/components/schemas/ShopeePay-Refund" },
                    { "$ref": "#/components/schemas/DANA-Pending" },
                    { "$ref": "#/components/schemas/DANA-Success" },
                    { "$ref": "#/components/schemas/DANA-Refund" }
                  ]
                },
                "examples": {
                  "OVO-OpenAPISale-Pending": {
                    "summary": "OVO Open API Sale - Pending",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "2020102900000000000001",
                      "originalReferenceNo": "2020102977770000000009",
                      "originalExternalId": "30443786930722726463280097920912",
                      "serviceCode": "55",
                      "latestTransactionStatus": "03",
                      "transactionStatusDesc": "PENDING",
                      "originalResponseCode": "2005503",
                      "originalResponseMessage": "Request has been processed successfully",
                      "paidTime": "2020-12-21T14:56:11+07:00",
                      "transAmount": {
                        "value": "112345678.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "OVO SNAP Direct Debit"
                        }
                      }
                    }
                  },
                  "OVO-OpenAPISale-SuccessPayment": {
                    "summary": "OVO Open API Sale - Success Payment",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "2020102900000000000001",
                      "originalReferenceNo": "2020102977770000000009",
                      "originalExternalId": "30443786930722726463280097920912",
                      "serviceCode": "55",
                      "latestTransactionStatus": "00",
                      "transactionStatusDesc": "SUCCESS",
                      "originalResponseCode": "2005503",
                      "originalResponseMessage": "Request has been processed successfully",
                      "paidTime": "2020-12-21T14:56:11+07:00",
                      "transAmount": {
                        "value": "112345678.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "OVO SNAP Direct Debit"
                        }
                      }
                    }
                  },
                  "OVO-OpenAPISale-Refund": {
                    "summary": "OVO Open API Sale - Refund",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Request has been processed successfully",
                      "originalPartnerReferenceNo": "2020102900000000000001",
                      "originalReferenceNo": "2020102977770000000009",
                      "originalExternalId": "30443786930722726463280097920912",
                      "serviceCode": "55",
                      "latestTransactionStatus": "04",
                      "transactionStatusDesc": "REFUNDED",
                      "originalResponseCode": "2005500",
                      "originalResponseMessage": "Request has been processed successfully",
                      "refundHistory": [
                        {
                          "refundNo": "96194816941239812",
                          "partnerReferenceNo": "239850918204981205970",
                          "refundAmount": {
                            "value": "12345678.00",
                            "currency": "IDR"
                          },
                          "refundStatus": "00",
                          "refundDate": "2020-12-23T07:44:16+07:00",
                          "reason": "Customer Complain"
                        },
                        {
                          "refundNo": "96194123981251341",
                          "partnerReferenceNo": "2398509123131981205970",
                          "refundAmount": {
                            "value": "112345678.00",
                            "currency": "IDR"
                          },
                          "refundStatus": "00",
                          "refundDate": "2020-12-23T07:54:16+07:00",
                          "reason": "Customer Complain"
                        }
                      ],
                      "transAmount": {
                        "value": "112345678.00",
                        "currency": "IDR"
                      },
                      "paidTime": "2020-12-21T14:56:11+07:00",
                      "additionalInfo": {
                        "acquirer": {
                          "id": "OVO SNAP Direct Debit"
                        }
                      }
                    }
                  },
                  "OVO-OpenAPIRecurring-SuccessPayment": {
                    "summary": "OVO Open API Recurring - Success Payment",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "2020102900000000000001",
                      "originalReferenceNo": "2020102977770000000009",
                      "originalExternalId": "30443786930722726463280097920912",
                      "serviceCode": "55",
                      "latestTransactionStatus": "00",
                      "transactionStatusDesc": "SUCCESS",
                      "originalResponseCode": "2005500",
                      "originalResponseMessage": "Request has been processed successfully",
                      "paidTime": "2020-12-21T14:56:11+07:00",
                      "transAmount": {
                        "value": "112345678.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "OVO SNAP Direct Debit"
                        }
                      }
                    }
                  },
                  "OVO-OpenAPIRecurring-Refund": {
                    "summary": "OVO Open API Recurring - Refund",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Request has been processed successfully",
                      "originalPartnerReferenceNo": "2020102900000000000001",
                      "originalReferenceNo": "2020102977770000000009",
                      "originalExternalId": "30443786930722726463280097920912",
                      "serviceCode": "55",
                      "latestTransactionStatus": "04",
                      "transactionStatusDesc": "REFUNDED",
                      "originalResponseCode": "2005500",
                      "originalResponseMessage": "Request has been processed successfully",
                      "refundHistory": [
                        {
                          "refundNo": "96194816941239812",
                          "partnerReferenceNo": "239850918204981205970",
                          "refundAmount": {
                            "value": "12345678.00",
                            "currency": "IDR"
                          },
                          "refundStatus": "00",
                          "refundDate": "2020-12-23T07:44:16+07:00",
                          "reason": "Customer Complain"
                        },
                        {
                          "refundNo": "96194123981251341",
                          "partnerReferenceNo": "2398509123131981205970",
                          "refundAmount": {
                            "value": "112345678.00",
                            "currency": "IDR"
                          },
                          "refundStatus": "00",
                          "refundDate": "2020-12-23T07:54:16+07:00",
                          "reason": "Customer Complain"
                        }
                      ],
                      "transAmount": {
                        "value": "112345678.00",
                        "currency": "IDR"
                      },
                      "paidTime": "2020-12-21T14:56:11+07:00",
                      "additionalInfo": {
                        "acquirer": {
                          "id": "OVO SNAP Direct Debit"
                        }
                      }
                    }
                  },
                  "ShopeePay-Pending": {
                    "summary": "ShopeePay - Pending",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "INV_SHOPEE_20231130115650",
                      "originalExternalId": "UAT_20231130115650143",
                      "serviceCode": "54",
                      "latestTransactionStatus": "03",
                      "transactionStatusDesc": "PENDING",
                      "originalResponseCode": "2005400",
                      "originalResponseMessage": "Successful",
                      "paidTime": "2023-11-30 11:56:50",
                      "transAmount": {
                        "value": "100000.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "SHOPEE_PAY"
                        }
                      }
                    }
                  },
                  "ShopeePay-Success": {
                    "summary": "ShopeePay - Success",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "INV_SHOPEE_20231130115650",
                      "originalReferenceNo": "h0v9Z34vyX",
                      "originalExternalId": "UAT_20231130115650143",
                      "serviceCode": "54",
                      "latestTransactionStatus": "00",
                      "transactionStatusDesc": "SUCCESS",
                      "originalResponseCode": "2005400",
                      "originalResponseMessage": "Successful",
                      "paidTime": "2023-11-30 11:59:31",
                      "transAmount": {
                        "value": "100000.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "SHOPEE_PAY"
                        }
                      }
                    }
                  },
                  "ShopeePay-Refund": {
                    "summary": "ShopeePay - Refund",
                    "value": {
                      "responseCode": "2005504",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "INV_SHOPEE_202407250004",
                      "originalReferenceNo": "161695845166492296",
                      "originalExternalId": "928573430",
                      "serviceCode": "55",
                      "latestTransactionStatus": "04",
                      "transactionStatusDesc": "REFUNDED",
                      "originalResponseCode": "2005400",
                      "originalResponseMessage": "Successful",
                      "paidTime": "2024-07-25T11:18:51+07:00",
                      "transAmount": {
                        "value": "3.00",
                        "currency": "IDR"
                      },
                      "refundHistory": [
                        {
                          "refundNo": "SHOPEE_202407250004_RFN3",
                          "partnerReferenceNo": "INV_SHOPEE_202407250004",
                          "refundAmount": {
                            "value": "3.00",
                            "currency": "IDR"
                          },
                          "refundStatus": "00",
                          "refundDate": "2024-07-25T11:32:12+07:00"
                        }
                      ],
                      "additionalInfo": {
                        "acquirer": {
                          "id": "Shopee Pay"
                        }
                      }
                    }
                  },
                  "DANA-Pending": {
                    "summary": "DANA - Pending",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "INV20240711007",
                      "originalReferenceNo": "rarPxBRuvdByoOnbmUrQqtVyz6UdgUgik2M0yyR98l10EeadmVnnq62pVMPCMR8W",
                      "originalExternalId": "307350227",
                      "serviceCode": "55",
                      "latestTransactionStatus": "03",
                      "transactionStatusDesc": "PENDING",
                      "originalResponseCode": "2005400",
                      "originalResponseMessage": "Successful",
                      "paidTime": "2024-07-11T14:23:55+07:00",
                      "transAmount": {
                        "value": "1.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "DANA Snap Direct Debit"
                        }
                      }
                    }
                  },
                  "DANA-Success": {
                    "summary": "DANA - Success",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "INV20240723006",
                      "originalReferenceNo": "20240723111212800110166234101713965",
                      "originalExternalId": "209469647",
                      "serviceCode": "55",
                      "latestTransactionStatus": "00",
                      "transactionStatusDesc": "SUCCESS",
                      "originalResponseCode": "2005400",
                      "originalResponseMessage": "Successful",
                      "paidTime": "2024-07-23T16:55:29+07:00",
                      "transAmount": {
                        "value": "1.00",
                        "currency": "IDR"
                      },
                      "additionalInfo": {
                        "acquirer": {
                          "id": "DANA Snap Direct Debit"
                        }
                      }
                    }
                  },
                  "DANA-Refund": {
                    "summary": "DANA - Refund",
                    "value": {
                      "responseCode": "2005500",
                      "responseMessage": "Successful",
                      "originalPartnerReferenceNo": "INV20240723006",
                      "originalReferenceNo": "20240723111212800110166234101713965",
                      "originalExternalId": "209469647",
                      "serviceCode": "55",
                      "latestTransactionStatus": "04",
                      "transactionStatusDesc": "REFUNDED",
                      "originalResponseCode": "2005400",
                      "originalResponseMessage": "Successful",
                      "paidTime": "2024-07-23T16:55:29+07:00",
                      "transAmount": {
                        "value": "1.00",
                        "currency": "IDR"
                      },
                      "refundHistory": [
                        {
                          "refundNo": "RFN202407234",
                          "partnerReferenceNo": "INV20240723006",
                          "refundAmount": {
                            "value": "1.00",
                            "currency": "IDR"
                          },
                          "refundStatus": "00",
                          "refundDate": "2024-07-23T17:40:01+07:00"
                        }
                      ],
                      "additionalInfo": {
                        "acquirer": {
                          "id": "DANA Snap Direct Debit"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RequestBody": {
        "type": "object",
        "description": "Request body to get status of E-Wallet",
        "properties": {
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system",
            "example": "INV_SHOPEE_202407250004"
          },
          "originalReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service provider system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "API type indicator. Use : 55 for Check Status API",
            "example": 55
          },
          "transactionDate": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "example": "2020-12-21T14:56:11+07:00"
          },
          "amount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "2000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Value and Currency"
          },
          "merchantId": {
            "type": "string",
            "description": "Merchant identifier that is unique per each merchant",
            "example": "23489182303312"
          },
          "subMerchantId": {
            "type": "string",
            "description": "Sub merchant ID",
            "example": "23489182303312"
          },
          "externalStoreId": {
            "type": "string",
            "description": "External Store ID for merchant",
            "example": "183908924912387"
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "deviceId": {
                "type": "string",
                "example": "12345679237"
              },
              "channel": {
                "type": "string",
                "example": "mobilephone"
              }
            },
            "description": "Additional information"
          }
        },
        "required": ["serviceCode"]
      },
      "OVOSalePending": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "OVO SNAP Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "OVOSaleSuccess": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "OVO SNAP Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "OVOSaleRefund": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "approvalCode": {
            "type": "string",
            "description": "Unique number"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "refundNo": {
            "type": "string",
            "description": "Transaction Identifier on Service Provider System"
          },
          "partnerReferenceNo": {
            "type": "string",
            "description": "ReferenceNumber from PJP AIS for the refund."
          },
          "refundAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "ReferenceNumber from PJP AIS for the refund."
          },
          "refundStatus": {
            "type": "string",
            "description": "00 = Success",
            "required": "Conditional"
          },
          "refundDate": {
            "type": "string",
            "description": "(ISO 8601) Transaction date : dd-MM-yyyy ( Mandatory )\n HH:mm:Ss ( Optional )",
            "required": "Conditional"
          },
          "reason": {
            "type": "string",
            "description": "Refund reason."
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "OVO SNAP Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "OVO-OpenAPIRecurring-SuccessPayment": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "OVO SNAP Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "OVO-OpenAPIRecurring-Refund": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "approvalCode": {
            "type": "string",
            "description": "Unique number"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator (service code of the original transaction request)"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "refundNo": {
            "type": "string",
            "description": "Transaction Identifier on Service Provider System"
          },
          "partnerReferenceNo": {
            "type": "string",
            "description": "ReferenceNumber from PJP AIS for the refund."
          },
          "refundAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Net amount of the refund."
          },
          "refundStatus": {
            "type": "string",
            "description": "00 = Success",
            "required": "Conditional"
          },
          "refundDate": {
            "type": "string",
            "description": "(ISO 8601) Transaction date : dd-MM-yyyy ( Mandatory ),\n HH:mm:Ss ( Optional )",
            "required": "Conditional"
          },
          "reason": {
            "type": "string",
            "description": "Refund reason."
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "112345678.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "OVO SNAP Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "ShopeePay-Pending": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "100000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "SHOPEE_PAY"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "ShopeePay-Success": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "100000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "SHOPEE_PAY"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "ShopeePay-Refund": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "3.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "Shopee Pay"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "DANA-Pending": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "1000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "DANA Snap Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "DANA-Success": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "1000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "DANA Snap Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      },
      "DANA-Refund": {
        "type": "object",
        "required": [
          "responseCode",
          "responseMessage",
          "serviceCode",
          "latestTransactionStatus",
          "additionalInfo",
          "partnerReferenceNo",
          "refundAmount",
          "refundStatus",
          "aditionalInfo"
        ],
        "properties": {
          "responseCode": {
            "type": "string",
            "maxLength": 7,
            "description": "Response Code"
          },
          "responseMessage": {
            "type": "string",
            "maxLength": 150,
            "description": "Response Description"
          },
          "originalReferenceNo": {
            "type": "string",
            "maxLength": 200,
            "description": "Original transaction identifier on service provider system. ",
            "required": "Conditional"
          },
          "originalPartnerReferenceNo": {
            "type": "string",
            "description": "Original transaction identifier on service consumer system"
          },
          "originalExternalId": {
            "type": "string",
            "description": "Original External-ID on header message"
          },
          "serviceCode": {
            "type": "string",
            "description": "Transaction type indicator 55"
          },
          "latestTransactionStatus": {
            "type": "string",
            "description": "Unique identifier for this Payment from PJP. Mandatory if Payment happened.",
            "example": "00 = Success,\n01 = Initiated,\n02 = Paying,\n03 = Pending,\n04 = Refunded,\n05 = Canceled,\n06 = Failed,\n07 = Not Found"
          },
          "transactionStatusDesc": {
            "type": "string",
            "description": "Description status transaction"
          },
          "originalResponseCode": {
            "type": "string",
            "description": "Response code"
          },
          "originalResponseMessage": {
            "type": "string",
            "description": "Response description"
          },
          "refundNo": {
            "type": "string",
            "description": "Transaction Identifier on Service Provider System"
          },
          "partnerReferenceNo": {
            "type": "string",
            "description": "Transaction Identifier No"
          },
          "refundAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "1000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Refund Amount"
          },
          "refundStatus": {
            "type": "string",
            "description": "Refund Status"
          },
          "refundDate": {
            "type": "string",
            "description": "Refund Date"
          },
          "transAmount": {
            "type": "object",
            "properties": {
              "value": {
                "example": "1000.00"
              },
              "currency": {
                "example": "IDR"
              }
            },
            "description": "Transaction amount that will be paid using this payment method If it's IDR then value includes 2 decimal digits."
          },
          "additionalInfo": {
            "type": "object",
            "properties": {
              "acquirer": {
                "properties": {
                  "id": {
                    "example": "DANA Snap Direct Debit"
                  }
                }
              }
            },
            "description": "Additional information"
          },
          "paidTime": {
            "type": "string",
            "description": "transaction date : ISO 8601",
            "required": "Conditional"
          }
        }
      }
    }
  }
}
